config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 
  get '/about', to: 'home#about'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'users/:id/profile', to: 'users#profile', as: :users_profile
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'
  resources :users, only: [] do
    resource :relationships, only: [:create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  direct :cdn_image do |model, options|
    cdn_options = if Rails.env.development?
      Rails.application.routes.default_url_options
    else
      {
        protocol: 'https',
        port: 443,
        host: Rails.application.credentials.dig(:aws, :cdn_host)
      }
    end
  
    if model.respond_to?(:signed_id)
    route_for(
      :rails_service_blob_proxy,
      model.signed_id,
      model.filename,
      options.merge(cdn_options)
    )
    else
    signed_blob_id = model.blob.signed_id
    variation_key  = model.variation.key
    filename       = model.blob.filename
  
    route_for(
      :rails_blob_representation_proxy,
      signed_blob_id,
      variation_key,
      filename,
      options.merge(cdn_options)
    )
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "コメントの投稿に成功しました"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "コメントの投稿に失敗しました"
      @comments = @post.comments.order(created_at: :desc)
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    flash[:notice] = "コメントを削除しました"
    @post = Post.find(params[:post_id])
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
  <div class="row border-bottom border-grey pt-3 pb-3">
    <div class="col-md-1 col-2">
      <div class="text-center">
        <% if comment.user.icon.attached? %>
          <%= image_tag comment.user.icon.variant(resize_to_limit: [200, 200]), class: "sm-circle-image" %>
        <% else %>
          <%= image_tag ("icon.png"), size: '200x200', class: "sm-circle-image" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-11 col-10">
      <div class="d-flex justify-content-between mb-2">
        <div><%= comment.user.name %></div>
        <div class="d-flex">
          <div class="me-4"><%= comment.updated_at.to_s(:datetime_jp) %></div>
          <div><%= time_ago_in_words(comment.created_at) %>前</div>
        </div>
      </div>
      <div><%= comment.comment %></div>
      <% if comment.user == current_user %>
        <div class="comment_btn d-flex flex-row-reverse">
          <%= link_to "削除", "javascript:void(0)", "data-bs-toggle": "modal", "data-bs-target": "#CommentdeleteModal#{comment.id}" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="modal fade comment_delete_modal" id="CommentdeleteModal<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">削除確認</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">削除しますか？</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">やめる</button>
          <%= button_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger", data: { "turbolinks" => false } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: [post, comment], local: true) do |f| %>
    <%= f.text_area :comment, placeholder: "コメント", class: "form-control #{'is-invalid' if @comment.errors['comment'].any? }" %>
    <%= render "shared/error", model: @comment, attribute: :comment %>
    <div class="float-end mt-3">
      <%= f.submit 'コメントする', class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>