config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 
  get '/about', to: 'home#about'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'users/:id/profile', to: 'users#profile', as: :users_profile
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'
  resources :users, only: [] do
    resource :relationships, only: [:create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  direct :cdn_image do |model, options|
    cdn_options = if Rails.env.development?
      Rails.application.routes.default_url_options
    else
      {
        protocol: 'https',
        port: 443,
        host: Rails.application.credentials.dig(:aws, :cdn_host)
      }
    end
  
    if model.respond_to?(:signed_id)
    route_for(
      :rails_service_blob_proxy,
      model.signed_id,
      model.filename,
      options.merge(cdn_options)
    )
    else
    signed_blob_id = model.blob.signed_id
    variation_key  = model.variation.key
    filename       = model.blob.filename
  
    route_for(
      :rails_blob_representation_proxy,
      signed_blob_id,
      variation_key,
      filename,
      options.merge(cdn_options)
    )
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 500 }

  has_one_attached :icon
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :comment_posts, through: :comments, source: :post
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def liked_by?(post_id)
    likes.where(post_id: post_id).present?
  end

  def followed_by?(user_id)
    passive_relationships.find_by(following_id: user_id).present?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
      user.introduction = "よろしくお願いします。"
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i(update destroy)

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_profile_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_update_path_for(resource)
    edit_user_registration_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i(profile)
  before_action :set_user, only: %i(profile_edit profile_update account)
  before_action :ensure_normal_user, only: %i(profile_update)

  def profile
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).includes([images_attachments: :blob], [user: [icon_attachment: :blob]],
:likes).per(25)
    @followings = @user.followings.includes(icon_attachment: :blob)
    @followings_num = @followings.count
    @followers = @user.followers.includes(icon_attachment: :blob)
    @followers_num = @followers.count
    @comment_posts = @user.comment_posts.page(params[:page]).includes([images_attachments: :blob],
[user: [icon_attachment: :blob]], :likes, :comments).per(25)
    @like_posts = @user.like_posts.page(params[:page]).includes([images_attachments: :blob], [user: [icon_attachment: :blob]],
:likes).per(25)
  end

  def profile_edit
  end

  def profile_update
    if @user.update(user_params)
      flash[:notice] = "プロフィールの情報が更新されました"
      redirect_to users_profile_path(current_user)
    else
      flash[:alert] = "プロフィールの更新に失敗しました"
      render "profile_edit"
    end
  end

  def account
  end

  def ensure_normal_user
    if current_user.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :introduction, :icon)
  end
end

app/views/users/profile.html.erb
<div class="card text-center">
  <div class="mb-2 my-5">
    <% if @user.icon.attached? %>
      <%= image_tag @user.icon.variant(resize_to_limit: [200, 200]), class: "circle-image" %>
    <% else %>
      <%= image_tag ("icon.png"), size: '200x200', class: "circle-image" %>
    <% end %>
  </div>
  <div class="mb-2">
    <h2><%= @user.name %></h2>
  </div>
  <div class="mb-2">
    <span><%= link_to "#{@followers_num}フォロワー", 'javascript:void(0)', 'data-bs-toggle': "modal", 'data-bs-target': "#followersModal" %></span>　
    <span><%= link_to "#{@followings_num}フォロー中", 'javascript:void(0)', 'data-bs-toggle': "modal", 'data-bs-target': "#followingsModal" %></span>
  </div>
  <div class="modal fade" id="followersModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">フォロワー一覧</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% if @followers_num != 0 %>
          <div class="modal-body py-0">
            <% @followers.each_with_index do |follower, i| %>
              <%= link_to users_profile_path(follower), data: { "turbolinks" => false } do %>
                <div class="row align-items-center p-3 <%= " border-b-grey" if i != @followers_num - 1 %>">
                  <div class="col-2 text-center">
                    <% if follower.icon.attached? %>
                      <%= image_tag follower.icon.variant(resize_to_limit: [200, 200]), class: "sm-circle-image" %>
                    <% else %>
                      <%= image_tag ("icon.png"), size: '200x200', class: "sm-circle-image"  %>
                    <% end %>
                  </div>
                  <div class="col-10 text-start"><%= follower.name %></div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="modal-body">
            現在フォローワーはいません
          </div>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">戻る</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="followingsModal" tabindex="-1" role="dialog" aria-labelledby="1111" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">フォロー中一覧</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% if @followings_num != 0 %>
          <div class="modal-body py-0">
            <% @followings.each_with_index do |following, i| %>
              <%= link_to users_profile_path(following), data: { "turbolinks" => false } do %>
                <div class="row align-items-center p-3 <%= " border-b-grey" if i != @followings_num - 1 %>">
                  <div class="col-2 text-center">
                    <% if following.icon.attached? %>
                      <%= image_tag following.icon.variant(resize_to_limit: [200, 200]), class: "sm-circle-image" %>
                    <% else %>
                      <%= image_tag ("icon.png"), size: '200x200', class: "sm-circle-image"  %>
                    <% end %>
                  </div>
                  <div class="col-10 text-start"><%= following.name %></div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="modal-body">
            現在フォローしているユーザーはいません
          </div>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">戻る</button>
        </div>
      </div>
    </div>
  </div>
  <% if @user == current_user %>
    <div class="mb-5">
      <%= link_to "編集", users_profile_edit_path, class: "btn btn-primary" %>
    </div>
  <% else %>
    <% if user_signed_in? %>
      <div class="mb-5">
        <% if @user.followed_by?(current_user.id) %>
          <%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="mb-5">
    <p><%= @user.introduction %></p>
  </div>
  <ul class="nav nav-tabs nav-fill">
    <li class="nav-item">
      <%= link_to "投稿一覧", "#own-post", class: "nav-link active", "data-bs-toggle": "tab" %>
    </li>
    <li class="nav-item">
      <%= link_to "コメントした投稿一覧", "#comment", class: "nav-link", "data-bs-toggle": "tab" %>
    </li>
    <li class="nav-item">
      <%= link_to "いいねした投稿一覧", "#like", class: "nav-link", "data-bs-toggle": "tab" %>
    </li>
  </ul>
  <div class="tab-content mt-5">
    <div id="own-post" class="tab-pane fade show active">
      <%= render "posts/post_list", posts: @posts %>
    </div>
    <div id="comment" class="tab-pane fade">
      <%= render "posts/post_list", posts: @comment_posts %>
    </div>
    <div id="like" class="tab-pane fade">
      <%= render "posts/post_list", posts: @like_posts %>
    </div>
  </div>
</div>

app/views/users/profile_edit.html.erb
<%= form_with model: @user, url: users_profile_update_path do |f| %>
  <% if current_user.email == 'guest@example.com' %>
    <div class="error-box text-center mb-4 mx-auto w-sm-75 w-md-50">ゲストユーザーはプロフィール編集ができません。</div>
    <fieldset disabled >
  <% end %>
  <div class="card mb-4 mx-auto w-75">
    <div class="card-header"><div class="ms-md-3 lead">プロフィール編集</div></div>
    <div class="card-body mx-md-3 mt-3">
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :name, "名前", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control #{'is-invalid' if @user.errors['name'].any? }" %>
          <%= render "shared/error", model: @user, attribute: :name %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :introduction, "自己紹介", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :introduction, class: "form-control #{'is-invalid' if @user.errors['introduction'].any? }", rows: 8 %>
          <%= render "shared/error", model: @user, attribute: :introduction %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :icon, "アイコン画像", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.file_field :icon, class: "form-control #{'is-invalid' if @user.errors['icon'].any? }" %>
          <%= render "shared/error", model: @user, attribute: :icon %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user.email == 'guest@example.com' %>
    </fieldset>
  <% end %>
  <div class="d-flex justify-content-end w-75 mx-auto">
    <div>
      <%= link_to 'プロフィール画面に戻る', users_profile_path(current_user), class: "btn btn-outline-dark me-3", data: { "turbolinks" => false } %>
      <%= f.submit "更新", class: "btn btn-primary #{' disabled' if current_user.email == 'guest@example.com' }" %>
    </div>
  </div>
<% end %>