config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 
  get '/about', to: 'home#about'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'users/:id/profile', to: 'users#profile', as: :users_profile
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'
  resources :users, only: [] do
    resource :relationships, only: [:create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  direct :cdn_image do |model, options|
    cdn_options = if Rails.env.development?
      Rails.application.routes.default_url_options
    else
      {
        protocol: 'https',
        port: 443,
        host: Rails.application.credentials.dig(:aws, :cdn_host)
      }
    end
  
    if model.respond_to?(:signed_id)
    route_for(
      :rails_service_blob_proxy,
      model.signed_id,
      model.filename,
      options.merge(cdn_options)
    )
    else
    signed_blob_id = model.blob.signed_id
    variation_key  = model.variation.key
    filename       = model.blob.filename
  
    route_for(
      :rails_blob_representation_proxy,
      signed_blob_id,
      variation_key,
      filename,
      options.merge(cdn_options)
    )
    end
  end
end

app/views/shared/_error.html.erb
<% if model.errors.any? %>
  <div class="text-danger">
    <%= model.errors.full_messages_for(attribute).first %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-bg">
  <div class="container h-100 d-table">
    <div class="d-table-cell align-middle">
      <div class="text-start fit-content mx-auto">
        <small class="text-muted">ロゴは <%= link_to "DesignEvo", "https://www.designevo.com/jp/", title: "無料オンラインロゴメーカー" %> ロゴメーカーさんで作りました</small></br>
        <small class="text-muted">Kio Mukai &copy; All Right Reserved.</small>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand fixed-top header-bg p-3">
    <div class="container-fluid">
      <%= link_to "おみやげ広場", root_path, class: "navbar-brand mb-3", id: "logo", data: { "turbolinks" => false } %>
      <ul class="navbar-nav ms-auto align-items-center">
          <li class="nav-item me-2">
            <%= link_to "投稿", new_post_path, class: "btn btn-primary", data: { "turbolinks" => false } %>
          </li>
          <li class="nav-item btn-group">
            <ul class="navbar-nav dropdown-toggle d-flex align-items-center cursor-pointer" data-bs-toggle="dropdown">
              <% if current_user.icon.attached? %>
                <li class="nav-item"><%= image_tag cdn_image_url(current_user.icon.variant(resize_to_limit: [50, 50])), class: 'me-1 sm-circle-image' %></li>
              <% else %>
                <li class="nav-item"><%= image_tag ("icon.png"), size: "50x50", class: 'me-1 sm-circle-image' %></li>
              <% end %>
              <li class="nav-item"><%= current_user.name %></li>
            </ul>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to "おみやげ広場とは？", about_path, class: "dropdown-item", data: { "turbolinks" => false } %></li>
              <li><%= link_to "アカウント", edit_user_registration_path, class: "dropdown-item", data: { "turbolinks" => false } %></li>
              <li><%= link_to "プロフィール", users_profile_path(current_user), class: "dropdown-item", data: { "turbolinks" => false } %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item', data: { "turbolinks" => false } %></li>
              <li><%= link_to "退会する", 'javascript:void(0)', class: "dropdown-item", 'data-bs-toggle': "modal", 'data-bs-target': "#user-registration-destroy-modal" %></li>
            </ul>
          </li>
      </ul>
    </div>
  </nav>
  <div class="modal fade" id="user-registration-destroy-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">退会確認</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">退会するとデータは完全に削除され、復元することはできません。<br>本当にアカウントを削除しますか？</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">やめる</button>
          <%= button_to "削除", user_registration_path, method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <nav class="navbar navbar-expand-md fixed-top header-bg p-3">
    <div class="container-fluid">
      <%= link_to "おみやげ広場", root_path, class: "navbar-brand mb-2", id: "logo", data: { "turbolinks" => false } %>
      <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="avbarNav" aria-expanded="false" aria-label="ナビゲーション切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item px-md-2 nav-collapse-design nav-border-end"><%= link_to "おみやげ広場とは？", about_path, class: 'nav-link ', data: { "turbolinks" => false } %></li>
          <li class="nav-item px-md-2 nav-collapse-design nav-border-end"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link', data: { "turbolinks" => false } %></li>
          <li class="nav-item px-md-2 nav-collapse-design nav-border-end"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: 'nav-link', data: { "turbolinks" => false } %></li>
          <li class="nav-item px-md-2 nav-collapse-design"><%= link_to "ログイン", new_user_session_path, class: "nav-link", data: { "turbolinks" => false } %></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_like.html.erb
<div class="likes_buttons">
  <% if user_signed_in? %>
    <% if current_user.liked_by?(post.id) %>
      <object>
        <%= link_to post_like_path(id: post.id, post_id: post.id), method: :delete, remote: true do %>
          <div class="like-button"><i class="fas fa-heart fa-2x" style="color: #e8212a;"></i><span style="color: #e82a2a"><%= post.likes.count %></span></div>
        <% end %>      
      </object>
    <% else %>
      <object>
        <%= link_to post_likes_path(id: post.id, post_id: post.id), method: :post, remote: true do %>
          <div class="like-button"><i class="far fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= post.likes.count %></span></div>
        <% end %>        
      </object>
    <% end %>
  <% end %>
</div>