config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 
  get '/about', to: 'home#about'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get 'users/:id/profile', to: 'users#profile', as: :users_profile
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'
  resources :users, only: [] do
    resource :relationships, only: [:create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  direct :cdn_image do |model, options|
    cdn_options = if Rails.env.development?
      Rails.application.routes.default_url_options
    else
      {
        protocol: 'https',
        port: 443,
        host: Rails.application.credentials.dig(:aws, :cdn_host)
      }
    end
  
    if model.respond_to?(:signed_id)
    route_for(
      :rails_service_blob_proxy,
      model.signed_id,
      model.filename,
      options.merge(cdn_options)
    )
    else
    signed_blob_id = model.blob.signed_id
    variation_key  = model.variation.key
    filename       = model.blob.filename
  
    route_for(
      :rails_blob_representation_proxy,
      signed_blob_id,
      variation_key,
      filename,
      options.merge(cdn_options)
    )
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend Geocoder::Model::ActiveRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :address, presence: true
  validates :caption, presence: true, length: { maximum: 500 }

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.post_id) FROM likes where likes.post_id = posts.id GROUP BY likes.post_id)'
    Arel.sql(query)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i(show)
  before_action :set_post, only: %i(edit update destroy)

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to root_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render "new"
    end
  end

  def show
    @post = Post.includes(images_attachments: :blob).find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました"
      redirect_to root_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :caption, :address, :user_id, :latitude, :longitude, images: [])
  end
end

app/views/posts/_post_list.html.erb
<% if posts.present? %>
  <% posts.each do |post| %>
    <%= link_to post, data: { "turbolinks" => false } do %>
      <div class="post-item card mb-5 w-85 mx-auto <%= "ms-md-auto me-md-0" if current_page?(root_path) %>">
        <div class="card-header bg-transparent">
          <div class="row">
            <div class="col-md-2">
              <div class="fit-content mx-auto">
                <object>
                  <%= link_to users_profile_path(post.user) do %>
                    <div class="text-center">
                      <% if post.user.icon.attached? %>
                        <%= image_tag post.user.icon.variant(resize_to_limit: [200, 200]), class: "sm-circle-image" %>
                      <% else %>
                        <%= image_tag ("icon.png"), size: '200x200', class: "sm-circle-image" %>
                      <% end %>
                    </div>
                    <div class="text-center"><%= truncate(post.user.name, length: 10) %></div>
                  <% end %>
                </object>
              </div>
            </div>
            <div class="col-md-10 text-center text-md-start">
              <div><%= post.name %></div>
              <div><%= truncate(post.address, length: 20) %></div>
              <div class="d-flex justify-content-between">
                <div><%= post.updated_at.to_s(:datetime_jp) %></div>
                <div><%= time_ago_in_words(post.created_at) %>前</div>
              </div>
              <div class="d-flex justify-content-between">
                <div id="likes_btn_<%= post.id %>">
                  <%= render "likes/like", post: post %>
                </div>
                <% if user_signed_in? && post.user_id == current_user.id %>
                  <div class="btn-group">
                    <object><%= link_to "更新", [:edit, post], class: "btn btn-primary btn-sm me-3", data: { "turbolinks" => false } %></object>
                    <object><%= link_to "削除", 'javascript:void(0)', class: "btn btn-danger btn-sm", 'data-bs-toggle': "modal", 'data-bs-target': "#PostdeleteModal#{post.id}" %></object>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row m-3">
          <div class="col-lg-3 text-center mb-lg-0 mb-3">
          <% if post.images.present? %>
            <%= image_tag post.images[0].variant(resize_to_limit: [200, 200]), class: "product-image" %>
          <% else %>
            <%= image_tag ("no_image.png"), class: "product-image" %>
          <% end %>
          </div>
          <div class="col-lg-9 text-center text-lg-start"><%= truncate(post.caption, length: 165) %></div>
        </div>
      </div>
    <% end %>
    <div class="modal fade" id="PostdeleteModal<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">削除確認</h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">削除しますか？</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">やめる</button>
            <%= link_to "削除", post_path(post), method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="my-5 text-center">投稿が存在しません</p>
<% end %>
<%= paginate posts,theme: 'bootstrap-5', class: "mx-auto", data: { "turbolinks" => false }  %>

app/views/posts/edit.html.erb
<%= form_with model: @post do |f| %>
  <div class="card mb-4 mx-auto w-75">
    <div class="card-header"><div class="ms-md-3 lead">投稿更新</div></div>
    <div class="card-body mx-md-3 mt-3">
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :name, "おみやげ名", class: "col-form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, autofocus: true, placeholder: "おみやげ名", autocomplete: "name", class: "form-control #{'is-invalid' if @post.errors['name'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :name %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :address, "購入したお店", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :address, autofocus: true, placeholder: "購入したお店", class: "form-control #{'is-invalid' if @post.errors['address'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :address %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3"> 
          <%= f.label :caption, "おみやげ感想", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :caption, placeholder: "おみやげ感想", rows: "10", class: "form-control #{'is-invalid' if @post.errors['caption'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :caption %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :images, "おみやげ画像", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.file_field :images, multiple: true, class: "form-control #{'is-invalid' if @post.errors['images'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :image %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end w-75 mx-auto">
    <div>
      <%= link_to '投稿一覧へ戻る',root_path, class: "btn btn-outline-dark me-3", data: { "turbolinks" => false } %>
      <%= f.submit "更新", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: @post do |f| %>
  <div class="card mb-4 mx-auto w-75">
    <div class="card-header"><div class="ms-md-3 lead">新規投稿</div></div>
    <div class="card-body mx-md-3 mt-3">
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :name, "おみやげ名", class: "col-form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, autofocus: true, placeholder: "おみやげ名", autocomplete: "name", class: "form-control #{'is-invalid' if @post.errors['name'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :name %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :address, "購入したお店", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :address, autofocus: true, placeholder: "購入したお店", class: "form-control #{'is-invalid' if @post.errors['address'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :address %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3"> 
          <%= f.label :caption, "おみやげ感想", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :caption, placeholder: "おみやげ感想", rows: "10", class: "form-control #{'is-invalid' if @post.errors['caption'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :caption %>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md-3">
          <%= f.label :images, "おみやげ画像", class: "form-label mb-0" %>
          <div class="d-inline d-md-block">（複数投稿できます）</div>
        </div>
        <div class="col-md-8">
          <%= f.file_field :images, multiple: true, class: "form-control #{'is-invalid' if @post.errors['images'].any? }" %>
          <%= render "shared/error", model: @post, attribute: :image %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end w-75 mx-auto">
    <div class="button-group">
      <%= link_to '投稿一覧へ戻る', root_path, class: "btn btn-outline-dark me-3", data: { "turbolinks" => false } %>
      <%= f.submit "投稿", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="card mb-4 mx-auto">
  <div class="card-body">
    <div class="row">
      <div class="col-md-2">
        <%= link_to users_profile_path(@post.user) do %>
          <div class="text-center">
            <% if @post.user.icon.attached? %>
              <%= image_tag @post.user.icon.variant(resize_to_limit: [200, 200]), class: "sm-circle-image" %>
            <% else %>
              <%= image_tag ("icon.png"), size: '200x200', class: "sm-circle-image"  %>
            <% end %>
          </div>
          <div class="text-center"><%= @post.user.name %></div>
        <% end %>
      </div>
      <div class="col-md-10 text-center text-md-start">
        <div><%= @post.name %></div>
        <div><%= @post.address %></div>
        <div><%= @post.updated_at.to_s(:datetime_jp) %></div>
        <div class="d-flex justify-content-md-between justify-content-center">
          <div class="me-5 me-md-0" id="likes_btn_<%= @post.id %>">
            <%= render "likes/like", post: @post %>
          </div>
          <% if user_signed_in? && @post.user_id == current_user.id %>
            <div class="ms-5 ms-md-0 post_btn_group">
              <%= link_to "更新", [:edit, @post], class: "btn btn-primary btn-sm me-md-3 me-1",  data: { "turbolinks" => false } %>
              <%= link_to "削除", 'javascript:void(0)', class: "btn btn-danger btn-sm", 'data-bs-toggle': "modal", 'data-bs-target': "#PostdeleteModal" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal fade" id="PostdeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">削除しますか？</div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">やめる</button>
              <%= button_to "削除",post_path(@post),method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <ul class="nav nav-tabs nav-fill mt-4">
      <li class="nav-item">
        <%= link_to "トップ", "#top", class: "nav-link active", "data-bs-toggle": "tab" %>
      </li>
      <li class="nav-item">
        <%= link_to "場所", "#address", class: "nav-link", "data-bs-toggle": "tab" %>
      </li>
    </ul>
    <div class="tab-content mt-5 pb-5 border-bottom border-grey">
      <div id="top" class="tab-pane fade show active">
        <div class="row">
          <div class="col-md-5 text-center mb-md-0 mb-5 mx-auto">
            <% if @post.images.present? %>
              <div id="carouselIndicators" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                  <% @post.images.each_with_index do |image, i| %>
                    <li data-bs-target="#carouselIndicators" data-bs-slide-to="<%= i %>" class="<%= ' active' if i==0 %>" ></li>
                  <% end %>
                </ol>
                <div class="carousel-inner">
                  <% @post.images.each_with_index do |image, i| %>
                    <%= image_tag image.variant(resize_to_limit: [350, 350]), class: "carousel-item w-100 h-100 product-md-image #{" active" if i == 0} " %>
                  <% end %>
                </div>
                <%= link_to "#carouselIndicators", class: "carousel-control-prev", "data-bs-slide": "prev", role: "button" do %>
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">前に戻る</span>
                <% end %>
                <%= link_to "#carouselIndicators", class: "carousel-control-next", "data-bs-slide": "next", role: "button" do %>
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">次に送る</span>
                <% end %>
              </div>
            <% else %>
              <%= image_tag ("no_image.png"), class: "product-md-image w-100 h-100" %>
            <% end %>
          </div>
          <div class="col-md-7 text-center text-md-start"><%= @post.caption %></div>
        </div>
      </div>
      <div id="address" class="tab-pane fade">
        <p class="text-center mt-3"><%= @post.address %><p>
        <div class="map">
          <% if @post.latitude.present? && @post.longitude.present? %>
          <div id="map">
          </div>
          <% else %>
            <p class="my-5 text-center">該当するお店を地図に表示できませんでした</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row mt-5">
      <%= render "comments/form", comment: @comment, post: @post %>
      <div id="comments_area" class="border-top border-grey mt-3">
        <%= render "comments/comment", comments: @comments %>
      </div>
    </div>
  </div>
</div>
<div>
  <%= link_to "投稿一覧へ戻る",  root_path, class: "btn btn-primary", data: { "turbolinks" => false } %>
</div>
<script type="text/javascript">
function initMap() {
  var position = {lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
  var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15, 
            center: position
            });
  var transitLayer = new google.maps.TransitLayer();
  transitLayer.setMap(map);
  var contentString = '場所：<%= @post.address %>';
  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });
  var marker = new google.maps.Marker({
                position:position,
                map: map,
                title: contentString
              });
  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= Rails.application.credentials.api[:key] %>&callback=initMap">
</script>